name: Distributed Lint, Test & Build

on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_VERBOSE_LOGGING: true

# Each push should cancel workflows in progress and start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Main - Orchestrator
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.2
    with:
      parallel-commands: |
        npx nx workspace-lint
        npx nx format:check
      # parallel-commands-on-agents: |
      #   npx nx affected --target=lint --parallel=3
      #   npx nx affected --target=test --parallel=3 --ci --code-coverage
      #   npx nx affected --target=build --parallel=3

  agents:
    name: Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.2
    with:
      number-of-agents: 3
